name: Deploy artifacts

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: "Release version"
        default: ""
        required: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Apply next release version
      if: ${{ github.event.inputs.release-version != '' }}
      run: sed -i -r 's/currentVersion\s*=.*/currentVersion = ${{ github.event.inputs.release-version }}/' gradle.properties
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
#    - uses: extractions/netrc@v1 # Use this action to create a .netrc file for the buf.build machine
#      with:
#        machine: buf.build
#        username: ${{ secrets.BUF_USERNAME }}
#        password: ${{ secrets.BUF_TOKEN }}
    - name: Build with Gradle
      env:
        REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        TZ: "Asia/Seoul"
      run: ./gradlew clean publish
