name: semantic-release-prod
on:
  workflow_dispatch:
  push:
    paths-ignore:
    - ".github/**"
    branches:
    - "main"
jobs:
  semantic-release:
    runs-on: ubuntu-latest
    outputs:
      next-release-version: ${{ steps.get-next-release-version.outputs.NEXT_RELEASE_VERSION }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: echo REPO_TOKEN
      run: echo ${{ secrets.REPO_TOKEN }}
    - name: Get next release version
      id: get-next-release-version
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        GH_TOKEN: ${{ secrets.REPO_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/${{ secrets.REPO_USERNAME }}/gradle-version-catalog.git
        npx semantic-release
  start-workflows:
    strategy:
      matrix:
        workflows: [
          { workflow_id: "deploy-maven-repo.yaml" },
        ]
    needs: [ semantic-release ]
    runs-on: ubuntu-latest
    steps:
    - name: Start workflows
      if: ${{ needs.semantic-release.outputs.next-release-version != '' }}
      run: gh workflow run ${{ matrix.workflows.workflow_id }} --ref v${{ needs.semantic-release.outputs.next-release-version }} --repo ${{ github.repository }} -F release-version=${{ needs.semantic-release.outputs.next-release-version }}
      env:
        GH_TOKEN: ${{ secrets.REPO_TOKEN }}
